--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/will/.config/wpg/wallpapers/City.jpg"

-- Special
background="#1c1f26"
foreground="#dbd8da"
cursor="#dbd8da"

-- Colors
color0="#1c1f26"
color1="#e37e74"
color2="#a2e374"
color3="#325491"
color4="#74a2e3"
color5="#99B0D9"
color6="#90B4E7"
color7="#dbd8da"
color8="#2d323d"
color9="#e37e74"
color10="#a2e374"
color11="#325491"
color12="#74A2E3"
color13="#99B0D9"
color14="#90B4E7"
color15="#dbd8da"
