# Shell variables
# Generated by 'wal'
wallpaper='/home/will/.config/wpg/wallpapers/City.jpg'

# Special
background='#1c1f26'
foreground='#dbd8da'
cursor='#dbd8da'

# Colors
color0='#1c1f26'
color1='#e37e74'
color2='#a2e374'
color3='#325491'
color4='#74a2e3'
color5='#99B0D9'
color6='#90B4E7'
color7='#dbd8da'
color8='#2d323d'
color9='#e37e74'
color10='#a2e374'
color11='#325491'
color12='#74A2E3'
color13='#99B0D9'
color14='#90B4E7'
color15='#dbd8da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
